use individualdb; 

Insert into User (user_name, user_password) values ('geodow06', 'mattisgay123'); 
Insert into User (user_name, user_password) values ('geohai06', 'mattisafag123');  
Insert into User (user_name, user_password) values ('matgad06', 'iisgay123');  
Insert into Algorithm (alg_name, alg_moves, alg_scramble) values ('J', 'U R F', 'R U F R U');
Insert into Algorithm (alg_name, alg_moves, alg_scramble) values ('H', 'U F', 'R U F U');
Insert into Algorithm (alg_name, alg_moves, alg_scramble) values ('Z', 'U R', 'R F R U');
select * from user; 
select * from algorithm;  
insert into Times (time, alg_id, user_id) values ('20', '1','1');  
insert into Times (time, alg_id, user_id) values ('23', '1','1'); 
insert into Times (time, alg_id, user_id) values ('26', '2','1'); 
insert into Times (time, alg_id, user_id) values ('10', '1','2'); 
insert into Times (time, alg_id, user_id) values ('20', '2','3'); 
insert into Times (time, alg_id, user_id) values ('20', '1','3'); 
select * from Times; 
update user set user_password='mattisgay123' where user_id=1; 
select user_id, alg_id, avg(time) from (select user_id, alg_id, time from times where user_id=1) as user1times where alg_id=1;
select alg_id, avg(time) from (select * from times where user_id = 1) as user1 group by alg_id; 
select * from times order by time desc; 
select alg_id, avg(time) from (select * from times where user_id=1) as user1 where alg_id=1 order by time desc Limit 3; 