INSERT INTO ALgorithm (alg_id, alg_name, alg_moves, alg_scramble) VALUES (1, 'J2', 'R U R'' F'' R U R'' U'' R'' F R2 U'' R'' U''')
INSERT INTO Algorithm (alg_id, alg_name, alg_moves, alg_scramble) VALUES (2, 'T', 'R U R'' U'' R'' F R2 U'' R'' U'' R U R'' F''')
INSERT INTO Algorithm (alg_id, alg_name, alg_moves, alg_scramble) VALUES (3, 'H', 'M2 U M2 U2 M2 U M2') 
Insert into User (user_id, user_name, user_password) values (1, 'geodow06', 'password1') 
Insert into User (user_id, user_name, user_password) values (2, 'geohai06', 'password2')
Insert into User (user_id, user_name, user_password) values (3, 'matgad06', 'password3') 
insert into Time (time_id, time, alg_id, user_id) values (1, 20, 1, 1) 
insert into Time (time_id, time, alg_id, user_id) values (2, 21, 2, 1)
insert into Time (time_id, time, alg_id, user_id) values (3, 22, 1, 1)
insert into Time (time_id, time, alg_id, user_id) values (4, 23, 2, 2)
insert into Time (time_id, time, alg_id, user_id) values (5, 24, 3, 3)
insert into Time (time_id, time, alg_id, user_id) values (6, 25, 3, 3)
